name: weather_clean
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ionicons: ^0.1.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.0
  intl: ^0.18.1
  retrofit: ^4.1.0
  cached_network_image: ^3.2.0
  json_annotation: ^4.8.1
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
